version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Sales data from the raw dataset
      - name: product 
        identifier: raw_gz_product 
        description:  product data from the raw dataset
      - name : ship
        identifier: raw_gz_ship
        description:  sip data from the raw dataset